[features]
seeds = false
skip-lint = false

[programs.devnet]
credible = "Htue6EwooAPDGUYaVpU6A9Tip7upVUMYJmXktbSoqQH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./new-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
