[toolchain]
anchor_version = "0.29.0"  # Replace with the version you just installed

[features]
seeds = false
skip-lint = false

[programs.localnet]
certificate = "9hJYuQXybHoguzW5gxBcx2iFbgWzGvYUX6SzXLEA77gD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "D:/Solana/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
